import { type ArgTypes } from '@storybook/angular';

export const hideControlInput = {
  control: false,
};

export const hideControlRow = {
  table: {
    disable: true,
  },
};

export const hideAutoGeneratedControlType = {
  table: {
    type: {
      summary: null,
    },
  },
};

export function hideAllControlRows<T extends {}>(
  metaArgTypes: Partial<ArgTypes<T>> | undefined,
): {[p: string]: { table: { disable: boolean }}} {
  if (!metaArgTypes) {
    return {};
  }
  return {
    ...Object.fromEntries(Object.keys(metaArgTypes).map(key => ([key, hideControlRow]))),
  };
}
