name: "Reusable action: publish the Extra-Clarity package to NPM"

description: ""

inputs:
  lib-artifact-name:
    required: true
    type: string
    default: "extra-clarity-build"
    description: "Name of the extra-clarity package build available via artifacts"
  lib-dist-path:
    required: true
    type: string
    default: "dist/extra-clarity"
    description: "Path to the built extra-clarity package's files"
  node-version:
    type: string
    required: false
    default: 22
  npm-registry-url:
    type: string
    required: false
    default: https://registry.npmjs.org/
  secrets-npm-token:
    type: string
    required: true

runs:
  using: "composite"
  steps:
    - uses: actions/setup-node@v4
      with:
        node-version: ${{ inputs.node-ver }}
        registry-url: ${{ inputs.npm-registry-url }}

    - uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.lib-artifact-name }}
        path: ${{ inputs.lib-dist-path }}

    - run: npm publish
      working-directory: ${{ inputs.lib-dist-path }}
      env:
        NODE_AUTH_TOKEN: ${{ inputs.secrets-npm-token }}
