import { type Meta, type StoryObj, componentWrapperDecorator } from '@storybook/angular';

import {
  DEFAULT_PERIOD_SEC,
  EcAutoRefreshGroupComponent,
} from '@extrawest/extra-clarity/auto-refresh-group';

import { hideAutoGeneratedControlType } from '../../helpers';

type Story = StoryObj<EcAutoRefreshGroupComponent>;

const meta: Meta<EcAutoRefreshGroupComponent> = {
  title: 'Components/Auto Refresh Group',
  component: EcAutoRefreshGroupComponent,
  decorators: [componentWrapperDecorator((story) => `<div style="max-width:380px">${story}</div>`)],
  argTypes: {
    locale: {},
    period: {
      table: {
        defaultValue: { summary: DEFAULT_PERIOD_SEC.toString() },
      },
    },
    refresh: {
      control: false,
      ...hideAutoGeneratedControlType,
    },
    autoRefreshToggled: {
      control: false,
      ...hideAutoGeneratedControlType,
    },
  },
};

export default meta;

// eslint-disable-next-line @typescript-eslint/naming-convention
export const AutoRefreshGroupStory: Story = {
  name: 'Auto Refresh Group',
  args: {
    locale: '',
    period: 10,
    useAutoRefresh: true,
    autoRefreshBlocked: false,
    autoRefreshEnabled: true,
    failed: false,
    refreshing: false,
  },
};
