name: 'Private: DO NOT run it directly!'

on:
  workflow_call:
    inputs:
      publish-to-npm:
        type: boolean
        required: true
      release-tag-full:
        type: string
        required: true
    secrets:
      npm-token:
        required: true
      github-token:
        required: true
      storybook-firebase-service-account:
        required: true

env:
  # disable Husky
  HUSKY: 0
  # name of the primary branch for releasing the latest version
  PRIMARY_RELEASING_BRANCH: main
  # artifact names (available on the github actions page after completing the workflow)
  LIB_ARTIFACT_NAME: extra-clarity-build
  # paths to specific folders & files
  LIB_DIST_PATH: dist/extra-clarity
  LIB_PACKAGE_JSON: projects/extra-clarity/package.json
  ROOT_PACKAGE_LOCK_JSON: package-lock.json
  NODE_MODULES_PATH: node_modules
  # settings for publishing the package
  NODE_VER: 22
  NPM_REGISTRY: https://registry.npmjs.org/
  # firebase settings from '.firebaserc' & 'firebase.json'
  SB_FIREBASE_PROJECT_ID: storybook-deploy
  SB_FIREBASE_HOSTING_TARGET: storybook-hosting-target
  SB_FIREBASE_HOSTING_SITE_LATEST: extra-clarity-docs # IMPORTANT: see the note below
  # script names from the main 'package.json' to be called with 'npm run'
  SCRIPT_BUILD_LIB: build:extra-clarity
  SCRIPT_RELEASE_NOTES: release-notes
  SCRIPT_BUILD_STORYBOOK: build:storybook

  # IMPORTANT: The string value of SB_FIREBASE_HOSTING_SITE_LATEST must be unique across
  # entire .firebaserc to be correctly replaced for secondary releasing branches, e.g.:
  # "extra-clarity-docs" -> "v17-extra-clarity-docs"

jobs:
  check-version:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      tag: ${{ steps.get-package-version.outputs.tag }}
      major: ${{ steps.get-package-version.outputs.major }}
      is-latest: ${{ steps.get-is-latest.outputs.is-latest }}
    steps:
      # uses: actions/checkout@v4 -- to make custom actions available from within the repository itself
      - uses: actions/checkout@v4
      - id: get-package-version
        uses: ./.github/actions/get-package-version
        with:
          extra-clarity-package-json: ${{ env.LIB_PACKAGE_JSON }}
          tag-full: ${{ inputs.release-tag-full }}
      - id: get-is-latest
        uses: ./.github/actions/get-is-latest
        with:
          tag: ${{ steps.get-package-version.outputs.tag }}
          major-version: ${{ steps.get-package-version.outputs.major }}
          primary-release-branch: ${{ env.PRIMARY_RELEASING_BRANCH }}

  build-extra-clarity:
    needs: [check-version]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      notes: ${{ steps.release-notes.outputs.notes }}
    steps:
      # uses: actions/checkout@v4 -- to make custom actions available from within the repository itself
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: node-modules-${{ runner.os }}-${{ hashFiles(env.ROOT_PACKAGE_LOCK_JSON) }}
      - if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - name: Building extra-clarity
        run: npm run ${{ env.SCRIPT_BUILD_LIB }}
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.LIB_ARTIFACT_NAME }}
          path: ${{ env.LIB_DIST_PATH }}
          if-no-files-found: error
      - name: Generate release notes for GitHub Releases
        id: release-notes
        uses: ./.github/actions/get-release-notes
        with:
          release-notes-script: ${{ env.SCRIPT_RELEASE_NOTES }}

  publish-package-to-npm:
    needs: [check-version, build-extra-clarity]
    if: inputs.publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      # uses: actions/checkout@v4 -- to make custom actions available from within the repository itself
      - uses: actions/checkout@v4
      - name: Evaluate a tag to be attached to the published npm package
        id: get-npm-tag
        uses: ./.github/actions/get-npm-tag
        with:
          major-version: ${{ needs.check-version.outputs.major }}
          is-latest: ${{ needs.check-version.outputs.is-latest }}
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VER }}
          registry-url: ${{ env.NPM_REGISTRY }}
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.LIB_ARTIFACT_NAME }}
          path: ${{ env.LIB_DIST_PATH }}
      - run: npm publish --tag ${{ steps.get-npm-tag.outputs.tag }}
        working-directory: ${{ env.LIB_DIST_PATH }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.npm-token }}

  create-github-release:
    needs: [check-version, build-extra-clarity, publish-package-to-npm]
    if: inputs.publish-to-npm
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          skipIfReleaseExists: true
          token: ${{ github.token }}
          tag: ${{ needs.check-version.outputs.tag }}
          name: ${{ needs.check-version.outputs.tag }}
          body: ${{ needs.build-extra-clarity.outputs.notes }}
          makeLatest: ${{ needs.check-version.outputs.is-latest }}

  build-and-publish-storybook:
    needs: [check-version, build-extra-clarity]
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        id: node-modules-cache
        with:
          path: ${{ env.NODE_MODULES_PATH }}
          key: node-modules-${{ runner.os }}-${{ hashFiles(env.ROOT_PACKAGE_LOCK_JSON) }}
      - if: ${{ steps.node-modules-cache.outputs.cache-hit != 'true' }}
        run: npm ci
      - uses: actions/download-artifact@v4
        with:
          name: ${{ env.LIB_ARTIFACT_NAME }}
          path: ${{ env.LIB_DIST_PATH }}
      - name: Building storybook
        run: npm run ${{ env.SCRIPT_BUILD_STORYBOOK }}
      - name: Override the configured firebase hosting site in .firebaserc for non-latest versions (adding a prefix vXX-)
        if: ${{ needs.check-version.outputs.is-latest != 'true' }}
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          include: .firebaserc
          find: ${{ env.SB_FIREBASE_HOSTING_SITE_LATEST }}
          replace: v${{ needs.check-version.outputs.major }}-${{ env.SB_FIREBASE_HOSTING_SITE_LATEST }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.github-token }}
          firebaseServiceAccount: ${{ secrets.storybook-firebase-service-account }}
          projectId: ${{ env.SB_FIREBASE_PROJECT_ID }}
          target: ${{ env.SB_FIREBASE_HOSTING_TARGET }}
          channelId: live
